[modengine]
debug = true

[mod_loader]
enabled = true
loose_params = true

[[mod_loader.mods]]
path = "AshesLauncher/Ashes/_ashes"
enabled = true

[scylla_hide]
enabled = true

[debug_menu]
enabled = true
boot_menu = true

[profiling]
enabled = true

[matchmaking]
enabled = true