[modengine]
debug = true

[mod_loader]
enabled = true
loose_params = true

[[mod_loader.mods]]
path = "AshesLauncher/_ashes"
enabled = true

[scylla]
enabled = true

[debug_menu]
enabled = true
boot_menu = true

[profiler]
enabled = true